Clean up data format of SSB population dataset
IT2901-SINTEF01/backend pull request #100
Opened 2021-03-24 12:30 UTC by FredrikAugust

Closes #94 

```graphql
query {
	populationsInNorway {
		# municipalitiesWithKeys
		dataset(years: ["2018", "2019", "2020", "2021"], municipalities: ["K-0301", "K-3024"]) {
			value {
				municipality
				populationForYear {
					year
					population
				}
			}
		}
	}
}
```

You can now use this format when requesting data, which is a bit easier to read and work with for @IT2901-SINTEF01/frontend.

2021-03-25 17:52 UTC, Kpaubert requested changes
Couple o'comments, looks good overall.

2021-03-25 17:52 UTC, Kpaubert commented on API/Queries/RootQuery.cs
> +using System.Collections.Generic;
This import is not used.

2021-03-25 17:52 UTC, Kpaubert commented on API/Queries/RootQuery.cs
>              Field<ForecastType>("forecast", "Latitude and Longitude defaults to the coordinates of Trondheim",
Not related to the PR, so this is just a note: this description does not describe the functionality of the query.

2021-03-25 17:52 UTC, Kpaubert commented on BackendTests/UnitTests/PopulationInNorwayDatasetTypeTests.cs
> +            var expected = new LabeledValue()
When not using `new()` _and_ using curly brackets to set the properties, the parenthesis are redundant when instantiating an object and can be removed. Change or let stay as is, I don't have any preference.

2021-03-25 17:52 UTC, Kpaubert commented on BackendTests/UnitTests/PopulationInNorwayTypeTests.cs
> +        private readonly PopulationInNorwayType objectGraph = new(new MetadataServiceMocked());
Let's get an underscore on this one (love the instantiation though `new(new ...)`).

2021-03-25 17:52 UTC, Kpaubert commented on BackendTests/UnitTests/PopulationInNorwayTypeTests.cs
> +        public void Years()
This is not a clear name.

2021-03-25 17:52 UTC, Kpaubert commented on BackendTests/UnitTests/PopulationInNorwayTypeTests.cs
> +        public void MunicipalitiesWithKeys()
Clarify what the test tests.

2021-03-25 17:52 UTC, Kpaubert commented on Models/Base/JsonStat/JsonStatDatasetType.cs
> +    public abstract class JsonStatDatasetType<T, TU> : ObjectGraphType<JsonStatDataset<T>>
With several generic types, I think it's preferable to name them `<T1, T2>`, or `<T, U>`.

2021-03-25 17:52 UTC, Kpaubert commented on Models/MetAPI/GraphQLTypes/ForecastType.cs
>  namespace Backend.Models.MetAPI.GraphQLTypes
Not changed in your PR, but perhaps assign the nullable field and type field for the last field in the ForecastType?

2021-03-25 17:52 UTC, Kpaubert commented on Models/SSBPopulationStatistics/GraphQLTypes/PopulationForYearType.cs
> +    public class PopulationForYearType : ObjectGraphType<PopulationForYear>
Unclear name imo, is it population for a given year? Population per year?

2021-03-25 17:52 UTC, Kpaubert commented on Models/SSBPopulationStatistics/GraphQLTypes/LabeledValueType.cs
> +    public class LabeledValueType : ObjectGraphType<LabeledValue>
This naming seems sort of unclear for the untrained eye, perhaps add msdocs on this?

2021-03-25 17:52 UTC, Kpaubert commented on Models/SSBPopulationStatistics/GraphQLTypes/PopulationInNorwayDatasetType.cs
> +using System;
Not used.

2021-03-25 17:52 UTC, Kpaubert commented on Models/SSBPopulationStatistics/GraphQLTypes/PopulationInNorwayDatasetType.cs
> +                    return (from municipality in municipalities
Nice :awooga:

2021-03-26 13:21 UTC, FredrikAugust commented on BackendTests/UnitTests/PopulationInNorwayTypeTests.cs
> +        public void Years()
Yes!

2021-03-26 13:34 UTC, Kpaubert approved these changes
Nice!

2021-03-29 14:48 UTC, merged

2021-03-29 14:48 UTC, FredrikAugust commented
Admin force rebase as the review dismissal only happened due to comment changes.