Clean up test structure and add additional tests
IT2901-SINTEF01/backend pull request #118
Opened 2021-04-05 18:54 UTC by FredrikAugust

Changelog
-----------
- Clean up test folder structure
- Add additional tests for services and resolutions

------------------------------------------------------------------------------------
Closes #117

2021-04-05 18:56 UTC, FredrikAugust commented
Hey Lewis? Is this where I get in? 🏎️

2021-04-07 10:11 UTC, fredrikbw requested changes
I didn't mark all of them in this review, but you should probably just run a code cleanup to get rid of some redundant declarations, at least on the BackendTests Project. 

Perhaps set up another issue just for running code cleanup on the entire solution (so that this PR doesn't change files that aren't relevant for this PR)

2021-04-07 10:11 UTC, fredrikbw commented on BackendTests/GraphQL/Resolvers/Helpers/DictionaryStringCollectionStringTypeTest.cs
> +                    {"key2", new Collection<string>(new List<string> {"value2"})},
```suggestion
                    {"key2", new Collection<string>(new List<string> {"value2"})}
```

2021-04-07 10:11 UTC, fredrikbw commented on BackendTests/GraphQL/Resolvers/Metadata/StoredMetadataTypeTest.cs
> +            return _storedMetadataType.GetField(fieldName).Resolver.Resolve(new ResolveFieldContext()
```suggestion
            return _storedMetadataType.GetField(fieldName).Resolver.Resolve(new ResolveFieldContext
```

2021-04-07 10:13 UTC, FredrikAugust commented
Good call, @fredrikbw. I'll take a look at it.

2021-04-07 10:15 UTC, Kpaubert approved these changes
Looking pretty darn good to me.

2021-04-07 11:49 UTC, fredrikbw approved these changes
Looks G to M

2021-04-07 11:57 UTC, merged